#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config window_gap 12

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config border_width 8

bspc config active_border_color "#282828"
bspc config normal_border_color "#282828"
bspc config focused_border_color "#282828"

rm $HOME/.cache/dunst.log
dunst --config $HOME/.config/dunst/dunstrc &
picom --config $HOME/.config/picom/picom.conf &

xsetroot -cursor_name left_ptr &
hsetroot -fill "$HOME/Pictures/Wallpapers/Drip.jpg"

~/.config/polybar/launch.sh

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

xset m 0 0 &
